# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 16:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.CharField(default='bjagjibgbaea', max_length=50, unique=True)),
                ('Product_name', models.CharField(max_length=50, unique=True)),
                ('Product_brand', models.CharField(max_length=250)),
                ('Product_year', models.CharField(max_length=250)),
                ('Product_price', models.IntegerField(unique=True)),
                ('Product_image', models.CharField(default='http://www.freeiconspng.com/uploads/no-image-icon-15.png', max_length=25000000)),
                ('Product_image1', models.CharField(default='http://www.freeiconspng.com/uploads/no-image-icon-15.png', max_length=25000000)),
                ('Product_image2', models.CharField(default='http://www.freeiconspng.com/uploads/no-image-icon-15.png', max_length=25000000)),
                ('Product_image3', models.CharField(default='http://www.freeiconspng.com/uploads/no-image-icon-15.png', max_length=25000000)),
                ('Product_image4', models.CharField(default='http://www.freeiconspng.com/uploads/no-image-icon-15.png', max_length=25000000)),
                ('Product_image5', models.CharField(default='http://www.freeiconspng.com/uploads/no-image-icon-15.png', max_length=25000000)),
                ('Product_details', models.CharField(max_length=11250)),
                ('Product_bids', models.IntegerField(default=0)),
                ('Product_each_bid_cost', models.IntegerField(default=500)),
                ('Product_MAX_bid', models.IntegerField(default=0)),
                ('Product_bid_percent', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userbids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.IntegerField()),
                ('Product_name', models.CharField(max_length=250)),
                ('userid', models.IntegerField(default=1)),
                ('bid_time', models.CharField(max_length=250)),
                ('bid_count', models.IntegerField()),
                ('pymnt_status', models.CharField(default=1, max_length=10)),
                ('cur_prdt_bid_price', models.IntegerField(default=500)),
                ('purpose', models.CharField(default=1, max_length=10)),
                ('payment_request_id', models.CharField(default=1, max_length=10)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
