# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import dreambuy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dreambuy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_id',
            field=models.CharField(default=dreambuy.models.prdtcode, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_price',
            field=models.IntegerField(),
        ),
    ]
