# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreambuy', '0003_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_id',
            field=models.IntegerField(default=-6923),
            preserve_default=False,
        ),
    ]
