# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-28 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreambuy', '0004_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
