# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-05 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreambuy', '0005_auto_20170829_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_price',
            field=models.IntegerField(),
        ),
    ]
