# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-05 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreambuy', '0006_auto_20170905_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_each_bid_cost',
            field=models.IntegerField(default='500'),
        ),
    ]
