# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-06 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreambuy', '0007_product_product_each_bid_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_image1',
            field=models.CharField(default='https://www.transparenttextures.com/patterns/asfalt-light.png', max_length=25000000),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_image2',
            field=models.CharField(default='https://www.transparenttextures.com/patterns/asfalt-light.png', max_length=25000000),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_image3',
            field=models.CharField(default='https://www.transparenttextures.com/patterns/asfalt-light.png', max_length=25000000),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_image4',
            field=models.CharField(default='https://www.transparenttextures.com/patterns/asfalt-light.png', max_length=25000000),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_image5',
            field=models.CharField(default='https://www.transparenttextures.com/patterns/asfalt-light.png', max_length=25000000),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image',
            field=models.CharField(default='https://www.transparenttextures.com/patterns/asfalt-light.png', max_length=25000000),
        ),
    ]
