# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-07 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreambuy', '0008_auto_20170906_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_image',
            field=models.CharField(default='http://www.freeiconspng.com/uploads/no-image-icon-15.png', max_length=25000000),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image1',
            field=models.CharField(default='http://www.freeiconspng.com/uploads/no-image-icon-15.png', max_length=25000000),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image2',
            field=models.CharField(default='http://www.freeiconspng.com/uploads/no-image-icon-15.png', max_length=25000000),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image3',
            field=models.CharField(default='http://www.freeiconspng.com/uploads/no-image-icon-15.png', max_length=25000000),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image4',
            field=models.CharField(default='http://www.freeiconspng.com/uploads/no-image-icon-15.png', max_length=25000000),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_image5',
            field=models.CharField(default='http://www.freeiconspng.com/uploads/no-image-icon-15.png', max_length=25000000),
        ),
    ]
