# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-07 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreambuy', '0010_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_brand',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_price',
            field=models.IntegerField(unique=True),
        ),
    ]
