# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-07 13:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dreambuy', '0011_auto_20170907_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='Product_name',
            field=models.CharField(default=datetime.datetime(2017, 9, 7, 13, 40, 46, 896251, tzinfo=utc), max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
