# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-07 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreambuy', '0014_auto_20170907_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='Product_name',
            field=models.CharField(default='2017-09-07 19:13:39.271753', max_length=250),
        ),
    ]
