# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-07 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreambuy', '0016_auto_20170907_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bids',
            new_name='userbids',
        ),
    ]
