# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreambuy', '0018_auto_20170917_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbids',
            name='userid',
            field=models.IntegerField(default=1),
        ),
    ]
