# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreambuy', '0019_userbids_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbids',
            name='purpose',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
