# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreambuy', '0020_userbids_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbids',
            name='payment_request_id',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
